name: App Practice Project
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Install dependnecies
        run: npm ci

      - name: Running lint
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Running test
        run: npm test
      - name: Checkout the Code
        uses: actions/checkout@v4

  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Build the code
        run: npm run build

      - name: Deploy the code
        run: echo "Deploying"
