name: App Practice Project
on: push
jobs:
  get-runner:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps:
      - run: echo "selected runner = ${{ runner.name }}"

  Lint:
    runs-on: ${{ needs.get-runner.outputs.RUNNER }}
    needs: get-runner
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Install dependnecies
        run: npm ci

      - name: Running lint
        run: npm run lint

  Test:
    runs-on: ${{ needs.get-runner.outputs.RUNNER }}
    needs: [get-runner, Lint]
    steps:
      - name: Running test
        run: npm test

  Build:
    runs-on: ${{ needs.get-runner.outputs.RUNNER }}
    needs: [get-runner, Test]
    steps:
      - name: Build the code
        run: npm run build

      - name: Deploy the code
        run: echo "Deploying"
